In [28]:
#%pip install pandas numpy
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [7]:
print(df.head())

   model_year  origin fuel_type         drivetrain  num_doors  \
0        2006  Europe  Gasoline  Front-wheel drive          4
1        2008  Europe    Diesel  Front-wheel drive          4
2        1996    Asia  Gasoline  Front-wheel drive          5
3        1989  Europe  Gasoline  Front-wheel drive          4
4        1994     USA    Diesel  Front-wheel drive          3

   engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                 2180              6       243.0            3870
1                 2390              6       272.0            4210
2                 2320              6       267.0            4240
3                 2130              6       258.0            4490
4                 2580              7       304.0            4510

   acceleration  fuel_efficiency_mpg
0           NaN                 31.9
1           NaN                 31.3
2          17.3                 27.5
3          18.7                 28.5
4          17.5                 31.0

In [8]:
print(pd.__version__)

3.0.6

In [9]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [10]:
print(df.info())
print(df.describe())
print(df.columns)
print(df.shape)
print(df.dtypes)

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB
None
         model_year    num_doors  engine_displacement  num_cylinders  \
count  10000.000000  10000.00000         10000.000000   10000.000000
mean    1999.549500      3.50400          2268.807000       6.035200
std       14.207925      0.95209           183.447355       0.542578
min     1975.000000      2.00000          1590.000000       4.000000
25%     1987.000000      3.00000          2150.000000       6.000000
50%     2000.000000      4.00000          2270.000000       6.000000
75%     2012.000000      4.00000          2390.000000       6.000000
max     2024.000000      5.00000          3110.000000       8.000000

        horsepower  vehicle_weight  acceleration  fuel_efficiency_mpg
count  9123.000000    10000.000000   9736.000000         10000.000000
mean    254.446016     4286.754000     18.888044            29.997700
std      22.844613      266.212491      1.279543             2.930245
min     171.000000     3320.000000     14.000000            19.800000
25%     239.000000     4110.000000     18.000000            28.000000
50%     254.000000     4280.000000     18.900000            30.000000
75%     270.000000     4470.000000     19.700000            31.900000
max     334.000000     5460.000000     23.800000            41.200000
Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='str')
(10000, 11)
model_year               int64
origin                     str
fuel_type                  str
drivetrain                 str
num_doors                int64
engine_displacement      int64
num_cylinders            int64
horsepower             float64
vehicle_weight           int64
acceleration           float64
fuel_efficiency_mpg    float64
dtype: object

In [11]:
print(df.shape)

(10000, 11)

In [12]:
print(df.describe())

         model_year    num_doors  engine_displacement  num_cylinders  \
count  10000.000000  10000.00000         10000.000000   10000.000000
mean    1999.549500      3.50400          2268.807000       6.035200
std       14.207925      0.95209           183.447355       0.542578
min     1975.000000      2.00000          1590.000000       4.000000
25%     1987.000000      3.00000          2150.000000       6.000000
50%     2000.000000      4.00000          2270.000000       6.000000
75%     2012.000000      4.00000          2390.000000       6.000000
max     2024.000000      5.00000          3110.000000       8.000000

        horsepower  vehicle_weight  acceleration  fuel_efficiency_mpg
count  9123.000000    10000.000000   9736.000000         10000.000000
mean    254.446016     4286.754000     18.888044            29.997700
std      22.844613      266.212491      1.279543             2.930245
min     171.000000     3320.000000     14.000000            19.800000
25%     239.000000     4110.000000     18.000000            28.000000
50%     254.000000     4280.000000     18.900000            30.000000
75%     270.000000     4470.000000     19.700000            31.900000
max     334.000000     5460.000000     23.800000            41.200000

In [13]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB
None

In [9]:
print(df["fuel_type"].unique())
print(df["fuel_type"].value_counts())
print(df["fuel_type"].nunique(dropna=False))

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str
fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64
3

In [11]:
#count columns with missing values
print(df.isnull().sum())

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [12]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [13]:
#Find the maximum fuel efficiency for cars from Asia
asia_max_fuel_efficiency = df[df["origin"] == "Asia"]["fuel_efficiency_mpg"].max()
print(asia_max_fuel_efficiency)

41.2

In [14]:
median_before = df["horsepower"].median()
print("Median horsepower before filling missing values:", median_before)

Median horsepower before filling missing values: 254.0

In [16]:
#most frequent value of horsepower
most_frequent_horsepower = df["horsepower"].mode()[0]
print("Most frequent horsepower:", most_frequent_horsepower)

Most frequent horsepower: 252.0

In [21]:
df["horsepower"] = df["horsepower"].fillna(most_frequent_horsepower)

In [23]:
median_after = df["horsepower"].median()
print("Median horsepower after filling missing values:", median_after)

Median horsepower after filling missing values: 252.0

In [27]:
asia_cars = df[df["origin"] == "Asia"]
print(asia_cars.shape[0])
selected_columns = asia_cars[["vehicle_weight", "model_year"]]
first_seven = selected_columns.head(7)
print(first_seven)

2994
    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [29]:
#Convert the table into a NumPy array called X
X = first_seven.to_numpy()
print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

In [35]:
XTX = X.T @ X
print(XTX)
XTX_inverse = np.linalg.inv(XTX)
print(XTX_inverse)

[[131950500  60750580]
 [ 60750580  28041424]]
[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

In [37]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w = XTX_inverse @ X.T @ y
print(w)
print(w.sum())
print("Regression weights:", w)
print("Sum of weights:", w.sum())

[0.13644777 0.2327492 ]
0.36919696904925486
Regression weights: [0.13644777 0.2327492 ]
Sum of weights: 0.36919696904925486